AllCops:
  Include:
  - "**/*.rake"
  - "**/Gemfile"
  - "**/Rakefile"
  Exclude:
  - "vendor/**/*"
  - "db/**/*"
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Rails:
  Enabled: true

Style/Encoding:
  EnforcedStyle: when_needed

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
  - "app/admin/data_source.rb"
  - "app/admin/data_table.rb"
  - "spec/**/*"
